### PR TITLE
New claycss.com design 1.0

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Merged, thanks!

**Comment by jbalsas** [comment]
😱 😱 💃 !!!

@Robert-Frampton, how and when were you planning to deploy it to live!?

**Comment by Robert-Frampton** [comment]
@jbalsas 

@pat270 is going to update some of the code snippets, once that's done we can deploy it whenever.

Is there a specific time you were hoping to deploy it by?

**Comment by jbalsas** [comment]
No, it's fine, whenever we're ready!

I actually wanted to ask @matuzalemsteles to work on the code snippets so we can add some of the clay-components and give it a more component-oriented approach rather than just html... what do you think?

**Comment by Robert-Frampton** [comment]
@jbalsas makes sense to me. I think we should at least have the html up first, then deploy the component code snippets once they are ready at a later time. 

That way everyone who is working on the clay components have a place to view the markup, as well as any product teams that are migrating their custom markup in Portal.

**Pull request closed without merging**
